/**
 * Rice Purity Test questions - Uniquely rephrased for originality and SEO
 * MPS = Member of the Preferred Sex
 */

export const TOTAL_QUESTIONS = 100;
export const MAX_SCORE = 100;

export const QUESTIONS: readonly string[] = [
  // --- Start: Relationship & comfort-focused questions (moved to front for better engagement)
  'Had an extended kissing session lasting multiple hours?',
  'Kissed someone in their intimate areas?',
  'Exchanged kisses on the chest or breast area?',
  'Received or given visible kissing marks (hickeys)?',
  'Reclined and kissed someone intimately?',
  'Kissed someone on the neck?',
  'Engaged in deep kissing in public view?',
  'Deep kissed someone (tongue kissing)?',
  'Lip-kissed someone outside your family?',
  'Kissed someone who isn\'t a blood relative?',
  'Danced extremely close with someone?',
  'Been in a committed romantic relationship?',
  'Gone out on a romantic date?',
  'Held someone\'s hand romantically?',
  'Played games involving removing clothing?',
  'Been in a sensual or intimate situation observed by someone else?',
  'Masturbated or engaged in self-pleasure?',
  'Self-stimulated while viewing explicit content?',
  'Self-pleasured while another person was present?',
  'Been discovered during self-stimulation?',
  'Used an object for self-pleasure?',
  'Viewed adult entertainment content?',
  'Shared a sensual massage with someone?',
  'Simulated sexual activity while fully clothed?',
  'Removed clothing or had it removed by someone you were drawn to?',
  'Showered together with someone you were attracted to?',
  'Received intimate touching on your lower body?',
  'Had someone touch your chest intimately?',
  'Had intimate manual contact with your genitals?',
  'Experienced sexual tension or frustration?',

  // --- Followed by the rest of the original list (keeps concept, moves deeper topics later)
  'Had sexual contact with an animal?',
  'Engaged in intimacy with a close family member?',
  'Watched someone in private moments without their knowledge or consent?',
  'Received or provided payment for sexual services?',
  'Caused pregnancy or became pregnant?',
  'Experienced a pregnancy-related health scare?',
  'Participated in anal sexual activity?',
  'Had sexual relations during menstruation?',
  'Recorded or appeared in intimate video or photo content?',
  'Had intimate partners numbering five or more?',
  'Been with multiple sexual partners within a 24-hour period?',
  'Attended a group sexual gathering?',
  'Participated in a three-person sexual encounter?',
  'Been diagnosed with a sexually transmitted infection?',
  'Underwent STI testing due to health concerns?',
  'Had unprotected sexual intercourse?',
  'Been someone\'s first sexual partner?',
  'Had relations with someone of significantly different age?',
  'Traveled cross-country primarily for an intimate encounter?',
  'Had a casual intimate meeting outside a committed relationship?',
  'Joined the mile-high club (airplane intimacy)?',
  'Been intimate while another person was knowingly nearby?',
  'Had relations while a parent or guardian was home?',
  'Had intimate relations in someone else\'s bed?',
  'Been intimate in water environments (pool, hot tub)?',
  'Had relations in a public or semi-public setting?',
  'Experienced outdoor intimacy?',
  'Had intimate relations inside a vehicle?',
  'Been intimate with someone you just met?',
  'Experimented with multiple sexual positions?',
  'Had numerous intimate encounters (10+) with a partner?',
  'Stayed intimate for an extended consecutive period?',
  'Had three or more intimate moments in a single night?',
  'Experienced sexual intercourse?',
  'Deliberately damaged or defaced property?',
  'Received a felony conviction?',
  'Been convicted of any criminal offense?',
  'Been arrested by law enforcement?',
  'Been handcuffed by police?',
  'Been questioned or interrogated by authorities?',
  'Fled from or attempted to escape law enforcement?',
  'Had law enforcement called to your location?',
  'Been to or seen a professional dancer at an adult venue?',
  'Gone streaking in public?',
  'Skinny-dipped in a body of water?',
  'Relieved yourself in public view?',
  'Received disciplinary suspension from school?',
  'Had a meeting with school disciplinary officials?',
  'Used hard drugs (methamphetamine, crack, heroin)?',
  'Tried drugs beyond marijuana?',
  'Used cannabis or marijuana?',
  'Smoked, vaped, or consumed tobacco?',
  'Experienced blackouts from alcohol?',
  'Pretended to be sober around authority figures?',
  'Consumed enough alcohol to get drunk?',
  'Participated in drinking games?',
  'Drank alcoholic beverages outside religious contexts?',
  'Arranged for someone to leave so you could be intimate?',
  'Been surprised during an intimate moment?',
  'Spent the night with someone you were attracted to?',
  'Incorporated adult toys into intimate relations?',
  'Engaged in oral sex?',
  'Received oral sex?',
  'Gave oral sex?',
  'Purchased contraceptive products?',
  'Committed infidelity in a relationship?',
  'Had intimate video conversations online?',
  'Exchanged explicit photos with someone?',
  'Sent sexually explicit messages online?',
  'Reached climax from a partner\'s touch?',
] as const;

export type QuestionId = number; // 0-indexed
